### ISSUE TITLE
Question: Does this app handle ECS throttling?

### ISSUE THREAD

**Issue by dawilliams** [in4it/ecs-deploy#12]
Hello,

We are dealing with a lot of rate limiting errors on **DescribeServices** calls to ECS.  Does this app handle rate limiting errors with retries or something like that?

**Comment by wardviaene** [comment]
Hi Dave,

It doesn't, we haven't been hitting rate limits so far, even with bigger clusters. Where are you experiencing the DescribeServices issues? In the UI, through an action, or by hitting the webhook? Could you attach the part of the log where it errors out?

There might be a lot of API calls going out if you have a lot of service/task activity. If you have tasks being constantly recreated, the webhook is hit a lot, and there might be a lot of calls being taken place. This part uses caching to avoid rate limiting, but it's not retrying when it hits limits.

-Edward

**Comment by dawilliams** [comment]
Edward

Sorry I should have mentioned that we experience this using another tool.  We are currently looking for other options and that's why I asked. The current tool we use queries for ECS deployment success using the DescribeServices call

**Comment by wardviaene** [comment]
Oh I see. Our checks aren't very aggressive. There's enough time between the checks not to hit the rate limits. The status is also stored in dynamodb, so the client doesn't hit the AWS API directly.

Where we do a lot of API calls, we cache the result in dynamodb, to avoid hitting the API excessively.
