### ISSUE TITLE
Question : Using with already created cluster and AS groups

### ISSUE THREAD

**Issue by anmoljagetia** [in4it/ecs-deploy#13]
Hi,

First of all, I would like to thank you for this brilliant piece of software! This looks like the missing piece from ECS itself, and running this should be very helpful for management of all things ECS.
I am struggling to run this, since I am a complete newbie when it comes to go, so can't seem to understand any of the code, and I would like to ask you, on instructions on how to run this, and configure to use with an ECS cluster, that runs with the help of a supported AS Group and the ELB required are also already spawned.

Thank you in advance!

Kind regards,
Anmol

**Comment by wardviaene** [comment]
Hi,

There's 2 ways to set it up. You can either:

1) Use the bootstrap method, which will create most the components necessary to get this running, including the ECS cluster and Load Balancer
2) You can run it on an existing ECS cluster, which is more evolved. You can find terraform templates to guide you at https://github.com/in4it/ecs-deploy/blob/master/examples/ecs-deploy.tf

You can find the IAM templates in https://github.com/in4it/ecs-deploy/tree/master/templates/iam

The easiest way to get started is to create:
* A security group for the ALB (you can enable port 80/443 to everyone if you're planning to make it public)
* An ECS security group (that allows traffic from the loadbalancer security group)
* A VPC with private/public subnets or only public subnets if you don't want to use a NAT gateway. 
* An ssh key (you can use ssh-keygen for this)
* A KMS key 

With this info, you can bootstrap your ECS cluster using the bootstrap command in the README. It's best to run this using an account that has unrestricted access.

-Edward

**Comment by anmoljagetia** [comment]
Thank you for such a prompt response!

Unfortunately, I don't have access to an unrestricted acocunt, meaning I have to be as precise with permissions as possible :(

Also, I downloaded the release binaries from the release page, and populated an env file, however I keep getting JWT_SECRET missing error :(

Is there like a for noob method of deploying this?

**Comment by wardviaene** [comment]
At the moment there's no easier way. We were planning to add some installation UI through the web interface, but didn't have the time yet to develop it.

If your getting JWT_SECRET missing and you defined it in your .env file and you're using localserver.sh from the examples, then your .env file might be in the wrong format, as JWT_SECRET doesn't seem to be picked up. You can also just execute it like this:
JWT_SECRET=abc OTHER_ENV_VAR=something ./ecs-deploy --server

You can also deploy it straight on ECS as a task (as shown in one of the example jsons). You'd then add the environments to the task definition.

-Edward

**Comment by navidurrahman** [comment]
Hi,

I followed all the steps as you instructed here but got the following error:

```
2018-11-02 01:00:57 INFO controller controller.go:739 Database is empty - starting app for the first time
panic: handlers are already registered for path ''/'

goroutine 1 [running]:
github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin.(*node).addRoute(0xc001a37920, 0xc00199b150, 0x1, 0xc00187c180, 0x6, 0x6)
	/go/src/github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin/tree.go:235 +0x95a
github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin.(*Engine).addRoute(0xc00041efc0, 0x12f8a9c, 0x3, 0xc00199b150, 0x1, 0xc00187c180, 0x6, 0x6)
	/go/src/github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin/gin.go:252 +0x145
github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin.(*RouterGroup).handle(0xc00041efc0, 0x12f8a9c, 0x3, 0x12f85d6, 0x1, 0xc000186388, 0x1, 0x1, 0x12f85d6, 0x1)
	/go/src/github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin/routergroup.go:71 +0x1d3
github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin.(*RouterGroup).GET(0xc00041efc0, 0x12f85d6, 0x1, 0xc000186388, 0x1, 0x1, 0x1, 0xc00041efc0)
	/go/src/github.com/in4it/ecs-deploy/vendor/github.com/gin-gonic/gin/routergroup.go:99 +0x7c
github.com/in4it/ecs-deploy/api.(*API).createRoutes(0xc0019a6a70)
	/go/src/github.com/in4it/ecs-deploy/api/api.go:87 +0x63f
github.com/in4it/ecs-deploy/api.(*API).Launch(0xc0019a6a70, 0xc0019a6a70, 0x0)
	/go/src/github.com/in4it/ecs-deploy/api/api.go:49 +0x78
main.main()
	/go/src/github.com/in4it/ecs-deploy/cmd/ecs-deploy/main.go:117 +0x1de
```

Any thoughts?

**Comment by wardviaene** [comment]
Yes, we never really intended to have no URL_PREFIX defined, so it's best to set one, as an environment variable: 

URL_PREFIX=/ecs-deploy

When using bootstrap this is set for you.

**Comment by navidurrahman** [comment]
thanks, @wardviaene working for me now, and testing it out :)

**Comment by navidurrahman** [comment]
I'm trying to build ecs-client on mac and getting the following error:

```
# github.com/in4it/ecs-deploy/api
../../go/src/github.com/in4it/ecs-deploy/api/api.go:184:3: cannot use func literal (type func(string, string, *gin.Context) (string, bool)) as type func(*gin.Context) (interface {}, error) in field value
../../go/src/github.com/in4it/ecs-deploy/api/api.go:191:3: cannot use func literal (type func(string, *gin.Context) bool) as type func(interface {}, *gin.Context) bool in field value
```

My go version:
go version go1.11.1 darwin/amd64

**Comment by wardviaene** [comment]
It's probably the gin-gonic dependency. It's best to use the following commands to ensure correct dependencies:
```
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh 
dep ensure
```
I also tagged gin-gonic to 1.3.0 just now, it was master before, because at the time of releasing, there was no tagged gin-gonic version for the features I needed.

**Comment by navidurrahman** [comment]
Thanks again, manage to solve this. Now, I'm trying to understand LoadBalancer integration. Is there a way to create a new load balancer?

I saw that deploying a new service, it will add the new rule in the main load balancer. Can i create a new load balancer with every service deployed?

**Comment by wardviaene** [comment]
You can create a new loadbalancer yourself (using for example terraform), then you can use "loadBalancer": "lb-name" within the ecs.json to use that loadbalancer.

We currently don't support the use-case of a loadbalancer per service, as you can easily create routes on a loadbalancer and distribute traffic. 1 LB per service might also get pretty expensive.

There's no deletion implemented yet. You can remove the service from ECS and remove the target group.
