### ISSUE TITLE
Couldn't start controller: dynamo: no item found

### ISSUE THREAD

**Issue by adenot** [in4it/ecs-deploy#3]
I'm getting this error when trying to run the container locally:

`Couldn't start controller: dynamo: no item found`

Using the command:

`docker run --env-file=.env in4it/ecs-deploy:0.0.6`
(same problem with :latest)

**Comment by wardviaene** [comment]
If you bootstrap, a new entry for the first deployment is immediately created in dynamodb. If you don't, then the resume returned "no item found" in database. I just merged a PR to fix this, a new version should be available shortly using :latest tag.

We're finishing a few improvements/features, 0.0.7 will be tagged/released next week.
